### ISSUE TITLE
Android: Camera still crashing on Android 11

### ISSUE THREAD

**Issue by XeduR** [coronalabs/corona#258]
This is a continuation of https://forums.solar2d.com/t/build-3644-accessing-camera-on-android-crashes/353459.

I haven't tested on Android 10.

The camera seems to work on Android 8 and 9, but on **Android 11**, however, Solar2D encounters the following error after giving the permission: "allow only while using the app."

Lua error
```
09:52:18.117     : Execute the lua listener task
09:52:18.119     : ERROR: CoronaActivity.DefaultRequestPermissiosnResultHandler.forwardRequestPermissionsResultToLua():Cannot forward results to Lua as no registry ID was found!
```

Device log:
```
06-22 11:29:01.010 21815 21815 W CAM_ActivityUiStartup: CameraActivityController failed!
06-22 11:29:01.010 21815 21815 W CAM_ActivityUiStartup: java.lang.IllegalStateException: GCA not granted write permission to content://com.solar2d.app.Camera.Test.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
06-22 11:29:01.010 21815 21815 W CAM_ActivityUiStartup:         at muj.n(PG:1)
06-22 11:29:01.010 21815 21815 W CAM_ActivityUiStartup:         at bly.r(PG:6)
```

Here's the same old Camera Test sample project that will demonstrate it.

First time that you tap the white rect, it'll request access to the camera. The second time that you tap it, it will launch the camera.
[Camera Test.zip](https://github.com/coronalabs/corona/files/7210806/Camera.Test.zip) (updated, but with same issues)

**Comment by XeduR** [comment]
Extended error log:

```
06-22 09:52:23.275 13229 13229 D AndroidRuntime: Shutting down VM
06-22 09:52:23.275 13229 13229 E AndroidRuntime: FATAL EXCEPTION: main
06-22 09:52:23.275 13229 13229 E AndroidRuntime: Process: com.google.android.GoogleCamera, PID: 13229
06-22 09:52:23.275 13229 13229 E AndroidRuntime: java.lang.RuntimeException: java.lang.IllegalStateException: GCA not granted write permission to content://com.solar2d.app.Camera.Test.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at jwc.run(PG:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at bso.run(Unknown Source:6)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-22 09:52:23.275 13229 13229 E AndroidRuntime: Caused by: java.lang.IllegalStateException: GCA not granted write permission to content://com.solar2d.app.Camera.Test.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at muj.n(PG:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at bly.r(PG:6)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at egi.<init>(PG:2)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at egj.a(PG:2)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at egz.get(PG:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at ofv.get(PG:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at ecb.F(PG:11)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at ecb.w(PG:54)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at bpc.b(PG:4)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at bpc.a(PG:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        at bvy.run(Unknown Source:1)
06-22 09:52:23.275 13229 13229 E AndroidRuntime:        ... 8 more
```

**Comment by Shchvova** [comment]
@XeduR crap... Unfortunately it does work on my device :/ (samsung galaxy)
What device are you using and what camera app do you have?

**Comment by XeduR** [comment]
I don't have access to the test device as it belongs to a client of mine. I've informed them to try out the camera again with the new build. I'm waiting to hear back from them and what device they've got, I'm guessing it's Pixel 2, and yeah, they are simulator builds.

**Comment by appfamily** [comment]
Pixel 2, built with simulator. Still crashes

```
06-30 11:18:54.704 26670 26670 E AndroidRuntime: FATAL EXCEPTION: main
06-30 11:18:54.704 26670 26670 E AndroidRuntime: Process: com.google.android.GoogleCamera, PID: 26670
06-30 11:18:54.704 26670 26670 E AndroidRuntime: java.lang.RuntimeException: java.lang.IllegalStateException: GCA not granted write permission to content://com.solar2d.app.Camera.Test.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at jwc.run(PG:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at bso.run(Unknown Source:6)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-30 11:18:54.704 26670 26670 E AndroidRuntime: Caused by: java.lang.IllegalStateException: GCA not granted write permission to content://com.solar2d.app.Camera.Test.files/cache/Picture1.jpg, the specified output in intent: Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list {...}} (has extras) }.
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at muj.n(PG:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at bly.r(PG:6)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at egi.<init>(PG:2)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at egj.a(PG:2)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at egz.get(PG:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at ofv.get(PG:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at ecb.F(PG:11)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at ecb.w(PG:54)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at bpc.b(PG:4)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at bpc.a(PG:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        at bvy.run(Unknown Source:1)
06-30 11:18:54.704 26670 26670 E AndroidRuntime:        ... 8 more
```

**Comment by appfamily** [comment]
So, stock Android camera

**Comment by appfamily** [comment]
Returning to this after the summer. Camera is no longer crashing, but there are other issues, see #274

**Comment by scottrules44** [comment]
I will try this on my Pixel 2 when I get home, but just wanted to let you know I am seeing this issue

**Comment by scottrules44** [comment]
I just got this error on my Pixel 2 will look into it

**Comment by appfamily** [comment]
Should this be addressed by https://github.com/coronalabs/corona/commit/581d8448923e50b3e408329c26cb4bc5b0e9155b?

**Comment by scottrules44** [comment]
No, a fix has not been found or implemented yet
