### ISSUE TITLE
Can't build apk with none target app store

### ISSUE THREAD

**Issue by ChaseTargaryen** [coronalabs/corona#288]
**Error  Description**
I'm using CoronaBuilder to build apk with no target app store. 
My Solar2d version is 3657.

<img width="533" alt="截圖 2021-10-14 下午4 58 39" src="https://user-images.githubusercontent.com/63695737/137286752-ad614a12-a4ec-4111-9fe1-bc34b0bd99f3.png">

**Platforms involved**
Building on: macOS 11.3
Building for: Android (none app store, not google play store)

**Attach your build.settings**
[buildsettings.txt](https://github.com/coronalabs/corona/files/7344527/buildsettings.txt)

**Full build log**
Enable full build log:
On macOS:
CoronaBuilder Params:

```
return params
CoronaBuilder: building project with 'temp/Android-Descriptors/FEF27.0.0-apk.lua'
Building app 'FE Connect'
	Version '27.0.0'
	Platform 'Android'
	PlatformVersion '40300'
	Project: '/Users/chaselee/apps/funbox/builds/FEF27.0.0-apk'
	Dst: '/Users/chaselee/apps/funbox/packages'
	Custom build id: 'none'
	Build type: 'distribution'
	Keystore path: '/Users/chaselee/apps/funbox/keystores/funenglish.keystore'
	Keystore alias: 'fe'
	Android version code: '7d301675'
	Android app package: 'net.studycat.testapp'
Oct 13 17:35:54.690: CoronaBuilder: Note: debug info is not being stripped from application (settings.build.neverStripDebugInfo = true)
```
```
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: net.studycat.testapp
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4403)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:22824)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:19693)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:745)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:929)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:23132)
	at android.os.Binder.shellCommand(Binder.java:597)
	at android.os.Binder.onTransact(Binder.java:495)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2671)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3941)
	at android.os.Binder.execTransact(Binder.java:704)
```

**Comment by ChaseTargaryen** [comment]
@schroederapps Sorry, my description were wrong.
I want to build APK with no target app strore and Solar2d 3657 is not letting me do it.

**Comment by Shchvova** [comment]
I increased RAM allowance with commit 36471b09525247b0998cd2ecb1ca7cb90b41de23.
I hope it'll fix the issue
