### ISSUE TITLE
[Android] permission

### ISSUE THREAD

**Issue by PaoUNetWork** [coronalabs/corona#313]
Hi, In the Android project, the onCreate method of the parent class CoronaActivity will get the AndroidID and clipboard functions. Can this part be executed later?Because I need to call these methods after the player agrees to the privacy policy.

clipboard
```
	at android.content.ClipboardManager.addPrimaryClipChangedListener(Native Method)
	at plugin.pasteboard.ClipboardListener$ApiLevel11$1.run(Unknown Source:21)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6549)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

AndroidID
```
	at android.provider.Settings$Secure.getStringForUser(Native Method)
	at android.provider.Settings$Secure.getString(Settings.java:4664)
	at com.ansca.corona.Controller.GetOSIdentifier(Unknown Source:12)
	at com.ansca.corona.Controller.getUniqueIdentifier(Unknown Source:30)
	at com.ansca.corona.NativeToJavaBridge.callGetUniqueIdentifier(Unknown Source:4)
	at com.ansca.corona.JavaToNativeShim.nativeRender(Native Method)
	at com.ansca.corona.JavaToNativeShim.render(Unknown Source:13)
	at com.ansca.corona.Controller.updateRuntimeState(Unknown Source:85)
	at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(Unknown Source:4)
	at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun(Unknown Source:390)
	at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(Unknown Source:24)
```

**Comment by scottrules44** [comment]
Which Android Project?

**Comment by Shchvova** [comment]
Both of this functions are called from APIs, and not invoked by Solar2D Itself. First one is when you initialize third party pasteboard plugin, second one is when you request ID from `system.getInfo` call. Don't perform this actions if you don't need to.
