### ISSUE TITLE
[anr issue]

### ISSUE THREAD

**Issue by PaoUNetWork** [coronalabs/corona#339]
**Some ANRS report errors. I want to know the reasons for these errors**

solar2D version:2020.3620

- error 1
``aInput Dispatching Timeout(at java.lang.Object.wait(Native method) - waiting on &lt;0x0f972312&gt; (a com.ansca.corona.graphics.opengl.GLSurfaceView$GLThreadManager) at java.lang.Object.wait(Object.java:442) at java.lang.Object.wait(Object.java:568) at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.surfaceDestroyed(unavailable:-1) - locked &lt;0x0f972312&gt; (a com.ansca.corona.graphics.opengl.GLSurfaceView$GLThreadManager) at com.ansca.corona.graphics.opengl.GLSurfaceView.surfaceDestroyed(unavailable:-1) at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView.surfaceDestroyed(unavailable:-1) at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:1976) at android.view.SurfaceView.updateSurface(SurfaceView.java:1205) at android.view.SurfaceView.setWindowStopped(SurfaceView.java:298) at android.view.SurfaceView.surfaceDestroyed(SurfaceView.java:1800) at android.view.ViewRootImpl.notifySurfaceDestroyed(ViewRootImpl.java:1983) at android.view.ViewRootImpl.setWindowStopped(ViewRootImpl.java:1939) at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:683) - locked &lt;0x01f59ae3&gt; (a java.lang.Object) at android.app.Activity.performStop(Activity.java:8363) at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5211) at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5190) at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5264) at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40) at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:263) at android.app.ActivityThread.main(ActivityThread.java:8283) at java.lang.reflect.Method.invoke(Native method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006) )``

- error 2
``Input Dispatching Timeout(native: #00 pc 0009232c  /apex/com.android.runtime/lib/bionic/libc.so (__epoll_pwait+20) native: #01 pc 00063fbd  /apex/com.android.runtime/lib/bionic/libc.so (epoll_wait+16) native: #02 pc 00011c9d  /system/lib/libutils.so (android::Looper::pollInner(int)+128) native: #03 pc 00011bc7  /system/lib/libutils.so (android::Looper::pollOnce(int， int*， int*， void**)+62) native: #04 pc 000bb6ef  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*， _jobject*， long long， int)+24) at android.os.MessageQueue.nativePollOnce(Native method) at android.os.MessageQueue.next(MessageQueue.java:339) at android.os.Looper.loop(Looper.java:200) at android.app.ActivityThread.main(ActivityThread.java:8262) at java.lang.reflect.Method.invoke(Native method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) )``

- error 3
``keyDispatchingTimedOut(  native: #00 pc 00048908  /system/lib/libc.so (__epoll_pwait+20)  native: #01 pc 0001b395  /system/lib/libc.so (epoll_pwait+36)  native: #02 pc 0001b3bd  /system/lib/libc.so (epoll_wait+12)  native: #03 pc 0000fd87  /system/lib/libutils.so (android::Looper::pollInner(int)+110)  native: #04 pc 0000fc81  /system/lib/libutils.so (android::Looper::pollOnce(int， int*， int*， void**)+32)  native: #05 pc 000b6a6d  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*， _jobject*， int)+24)  native: #06 pc 00196a6d  /system/framework/arm/boot-framework.oat (Java_android_os_MessageQueue_nativePollOnce__JI+92)  at android.os.MessageQueue.nativePollOnce(Native method)  at android.os.MessageQueue.next(MessageQueue.java:325)  at android.os.Looper.loop(Looper.java:176)  at android.app.ActivityThread.main(ActivityThread.java:7080)  at java.lang.reflect.Method.invoke(Native method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863))``

- error 4
``keyDispatchingTimedOut(  at java.lang.Object.wait(Native method)  at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.surfaceDestroyed(unavailable:-1)  at com.ansca.corona.graphics.opengl.GLSurfaceView.surfaceDestroyed(unavailable:-1)  at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView.surfaceDestroyed(unavailable:-1)  at android.view.SurfaceView.updateSurface(SurfaceView.java:719)  at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:319)  at android.view.View.dispatchDetachedFromWindow(View.java:17727)  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5341)  at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5312)  at android.view.ViewGroup.removeView(ViewGroup.java:5243)  at com.ansca.corona.CoronaRuntime.updateViews(unavailable:-1)  at 
**.onResume(unavailable:-1)  
**.onResume(unavailable:-1)  
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)  at **.ProxyInstrumentationImp.callActivityOnResume(ProxyInstrumentationImp.java:101)  at android.app.Activity.performResume(Activity.java:7438)  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3840)  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3916)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)  at android.os.Handler.dispatchMessage(Handler.java:106)  at android.os.Looper.loop(Looper.java:210)  at android.app.ActivityThread.main(ActivityThread.java:7080)  at java.lang.reflect.Method.invoke(Native method)  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863))``

**Comment by PaoUNetWork** [comment]
There is new anr issue form Google
**solar version: 3647**

**Occurs on Android SDK 11**
> backtrace:
  #00  pc 000000000000aab8  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/split_config.arm64_v8a.apk (offset 0x3f5000)
  #00  pc 0000000000102880  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000102790  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000115ecc  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000115204  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 00000000001170a8  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/oat/arm64/base.odex (art_jni_trampoline+152)
  #00  pc 00000000001b34d8  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/oat/arm64/base.odex (com.ansca.corona.Controller.updateRuntimeState+1032)
  #00  pc 00000000001cd2c8  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun+2664)
  #00  pc 00000000001cdf24  /data/app/~~dU2TVR1D_arV36A_8l2GdA==/com.**-eBcKH3hvlmEqQxzF-MqfLA==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run+228)
  #00  pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 00000000001a97e8  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #00  pc 000000000055e374  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460)
  #00  pc 00000000005ad5c4  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308)
  #00  pc 00000000000db188  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #00  pc 000000000007a9d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)



**Occurs on Android SDK 10**
>backtrace:
  #00  pc 000000000000aab8  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/split_config.arm64_v8a.apk
  #00  pc 0000000000102880  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000102790  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000115ecc  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 0000000000115204  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/split_config.arm64_v8a.apk!lib/arm64-v8a/libcorona.so (offset 0x88000)
  #00  pc 00000000000fd0a8  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/oat/arm64/base.odex (art_jni_trampoline+152)
  #00  pc 00000000001483d8  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/oat/arm64/base.odex (com.ansca.corona.Controller.updateRuntimeState+872)
  #00  pc 00000000002a06fc  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun+2668)
  #00  pc 000000000015f104  /data/app/com.**-jps9gQE8hMiv-1CnU3Gf-g==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run+228)
  #00  pc 0000000000137334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 0000000000145fec  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244)
  #00  pc 00000000004b16b0  /apex/com.android.runtime/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #00  pc 00000000004b27c4  /apex/com.android.runtime/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue const*)+416)
  #00  pc 00000000004f3180  /apex/com.android.runtime/lib64/libart.so (art::Thread::CreateCallback(void*)+1176)
  #00  pc 00000000000e69e0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36)
  #00  pc 0000000000084b6c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


**Occurs on Android SDK 12**

> backtrace:
  #00  pc 000000000000aab8  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/split_config.arm64_v8a.apk
  #00  pc 0000000000102880  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/split_config.arm64_v8a.apk!libcorona.so
  #00  pc 0000000000102790  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/split_config.arm64_v8a.apk!libcorona.so
  #00  pc 0000000000115ecc  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/split_config.arm64_v8a.apk!libcorona.so
  #00  pc 0000000000115204  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/split_config.arm64_v8a.apk!libcorona.so
  #00  pc 00000000000c1070  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/oat/arm64/base.odex (art_jni_trampoline+96)
  #00  pc 00000000000d5970  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/oat/arm64/base.odex (com.ansca.corona.Controller.updateRuntimeState+864)
  #00  pc 00000000000f5f50  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame+64)
  #00  pc 00000000000df4dc  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun+2636)
  #00  pc 000000000016b380  /data/app/~~x83OFfjStV4MT1KiWxQXCg==/com.**-pyhuVFRd3WDGUx0Y7zBjug==/oat/arm64/base.odex (com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run+240)
  #00  pc 00000000002cdd64  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #00  pc 0000000000317fb0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+156)
  #00  pc 00000000003cc480  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+380)
  #00  pc 000000000045eff0  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+992)
  #00  pc 00000000000b2fd0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  #00  pc 0000000000052834  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
