### ISSUE TITLE
Instant crash on Android 5.0.2 Nexus 7 building with Solar2D Release 3677

### ISSUE THREAD

**Issue by solares** [coronalabs/corona#437]
Self help steps before reporting the issue:
[ ] Check [Solar2D forums](https://forums.solar2d.com/) for a solution
[ ] If Android: make sure Java8 is installed and reported when running `java -version` and `javac -version` if not, download and install [Java 8](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html)

**Before reporting**
App crashes out immediately open opening, with 
" App stopped [ OK ] "
" Do you want to report crash  [ Yes ] [ No ]"

**Platforms involved**
Building on: macOS 12.5

Solar2D
https://github.com/coronalabs/corona/releases/tag/3677

Android 5.0.2

**Attach your build.settings**

[build.settings.zip](https://github.com/coronalabs/corona/files/9289679/build.settings.zip)

**Error**
```
java.lang.NoSuchMethodError: No virtual method isDeviceLocked()Z in class Landroid/app/KeyguardManager; or its super classes (declaration of 'android.app.KeyguardManager' appears in /system/framework/framework.jar)
```

**Full build log**
```
I/ActivityManager(  555): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.example.app cmp=com.example.app/com.ansca.corona.CoronaActivity bnds=[24,181][216,373] (has extras)} from uid 10036 on display 0
I/ActivityManager(  555): Start proc com.example.app for activity com.example.app/com.ansca.corona.CoronaActivity: pid=17731 uid=10073 gids={50073, 9997, 3003} abi=armeabi-v7a
W/ResourceType(17731): ResTable_typeSpec entry count inconsistent: given 8, previously 1
I/MultiDex(17731): VM with version 2.1.0 has multidex support
I/MultiDex(17731): Installing application
I/MultiDex(17731): VM has multidex support, MultiDex support library is disabled.
I/art     (17731): Thread[1,tid=17731,WaitingForJniOnLoad,Thread*=0xb5007800,peer=0x7327b2e0,"main"] recursive attempt to load library "/data/app/com.example.app-1/lib/arm/libjnlua5.1.so"
D/AndroidRuntime(17731): Shutting down VM
E/AndroidRuntime(17731): FATAL EXCEPTION: main
E/AndroidRuntime(17731): Process: com.example.app, PID: 17731
E/AndroidRuntime(17731): java.lang.NoSuchMethodError: No virtual method isDeviceLocked()Z in class Landroid/app/KeyguardManager; or its super classes (declaration of 'android.app.KeyguardManager' appears in /system/framework/framework.jar)
E/AndroidRuntime(17731):    at com.ansca.corona.SystemMonitor.isScreenLocked(SystemMonitor.java:142)
E/AndroidRuntime(17731):    at com.ansca.corona.CoronaActivity.requestResumeCoronaRuntime(CoronaActivity.java:2026)
E/AndroidRuntime(17731):    at com.ansca.corona.CoronaActivity.onResume(CoronaActivity.java:1843)
E/AndroidRuntime(17731):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
E/AndroidRuntime(17731):    at android.app.Activity.performResume(Activity.java:6019)
E/AndroidRuntime(17731):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
E/AndroidRuntime(17731):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
E/AndroidRuntime(17731):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
E/AndroidRuntime(17731):    at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(17731):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime(17731):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17731):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17731):    at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime(17731):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17731):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17731):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(17731):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
W/ActivityManager(  555):   Force finishing activity com.example.app/com.ansca.corona.CoronaActivity
E/        (  182): invalid crash request of size 4 (from pid=17535 uid=0)
I/WindowManager(  555): Screenshot max retries 4 of Token{1b051993 ActivityRecord{392fae82 u0 com.example.app/com.ansca.corona.CoronaActivity t34 f}} appWin=Window{f5c01c9 u0 Starting com.example.app} drawState=4
E/ActivityManager(  555): Invalid thumbnail dimensions: 720x720
I/OpenGLRenderer(  555): Initialized EGL, version 1.4
W/qcom_sensors_hal(  555): hal_sensor1_data_cb: SENSOR1_MSG_TYPE_BROKEN_PIPE
E/Diag_Lib(17763):  Diag_LSM_Init: Failed to open handle to diag driver, error = 2
E/Sensors (17763): sns_fsa_la.c(386):fsa: fflush failed, 9
E/Sensors (17763): sns_fsa_la.c(386):fsa: fflush failed, 9
W/Sensors (17763): sns_smr_la.c(446):smr_la: smr_apps_la_thread_main is starting, fd=11, sns_smr.en_rx_msg_ptr=b6f269d0
W/Sensors (17763): sns_sam_app.c(6827):sns_sam_reg_algo: Registering algo service 16, err 0
D/BoundBrokerSvc(14352): onBind: Intent { act=com.google.android.gms.udc.service.START dat=chimera-action:com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
D/BoundBrokerSvc(14352): Loading bound service for intent: Intent { act=com.google.android.gms.udc.service.START dat=chimera-action:com.google.android.gms.udc.service.START cmp=com.google.android.gms/.chimera.PersistentApiService }
D/BoundBrokerSvc(14352): onBind: Intent { act=com.google.android.gms.gmscompliance.service.START dat=chimera-action:com.google.android.gms.gmscompliance.service.START cmp=com.google.android.gms/.chimera.PersistentBoundBrokerService }
D/BoundBrokerSvc(14352): Loading bound service for intent: Intent { act=com.google.android.gms.gmscompliance.service.START dat=chimera-action:com.google.android.gms.gmscompliance.service.START cmp=com.google.android.gms/.chimera.PersistentBoundBrokerService }
E/Sensors (17763): sns_debug_main.c(565):Debug Config File missing in EFS!
E/qcom_sensors_hal(  555): hal_process_report_resp: Result: 1, Error: 5
E/qcom_sensors_hal(  555): hal_process_report_resp: 0 Error: 4 Reason: 16
E/qcom_sensors_hal(  555): hal_acquire_resources, hal_smgr_report_add() failed, handle=0
W/ActivityManager(  555): Activity pause timeout for ActivityRecord{392fae82 u0 com.example.app/com.ansca.corona.CoronaActivity t34 f}
I/ActivityManager(  555): Killing 15926:com.xiaomi.market/u0a87 (adj 15): empty #17
W/libprocessgroup(  555): failed to open /acct/uid_10087/pid_15926/cgroup.procs: No such file or directory
```

**Comment by scottrules44** [comment]
Are 100% sure this is with the newest build? I just ran a the sample code "DragMe" in on a nexus 7 emulator running Android 5 (21) with 36777 and did not get this crash.

<img width="551" alt="Screen Shot 2022-08-09 at 12 52 15 PM" src="https://user-images.githubusercontent.com/7820808/183725304-5a1658a0-ba53-4280-81ac-aa04d4a980a1.png">

**Comment by solares** [comment]
Thanks @scottrules44. You're right. We have got past the error with 3677, thanks for taking the time to reproduce this situation.
