### ISSUE TITLE
[ANDROID]: battery state plugin crash

### ISSUE THREAD

**Issue by IlSui** [coronalabs/corona#493]
I see some crashes from users devices mentioning the battery state plugin, and I think it could be fixed with a check inside the plugin:

`
java.lang.IllegalArgumentException: illegal index
        at com.naef.jnlua.LuaState.lua_setfield(LuaState.java:-2)
        at com.naef.jnlua.LuaState.setField(LuaState.java:1447)
        at com.ansca.corona.CoronaLua.newEvent(CoronaLua.java:103)
        at plugin.batteryState.LuaLoader$1.executeUsing(LuaLoader.java:129)
        at com.ansca.corona.CoronaRuntimeTaskDispatcher$TaskEvent.Send(CoronaRuntimeTaskDispatcher.java:179)
`

**Comment by scottrules44** [comment]
I pushed an update yesterday to fix this, should prevent this crash from happening
