### ISSUE TITLE
Google SSO crashes on new Huawei devices

### ISSUE THREAD

**Issue by mark-sgs** [coronalabs/corona#494]
Please update the plugin to handle devices where Google services are not installed.  Thank you.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.spheregamestudios.designercity/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4624)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4835)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2921)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9551)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at top.niunaijun.blackbox.client.hook.delegate.InstrumentationDelegate.execStartActivity(InstrumentationDelegate.java:359)
        at top.niunaijun.blackbox.client.hook.delegate.AppInstrumentation.execStartActivity(AppInstrumentation.java:222)
        at android.app.Activity.startActivityForResult(Activity.java:5630)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:5554)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zbe(com.google.android.gms:play-services-auth@@20.2.0:6)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(com.google.android.gms:play-services-auth@@20.2.0:14)
        at android.app.Activity.performCreate(Activity.java:8488)
        at android.app.Activity.performCreate(Activity.java:8461)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
        at top.niunaijun.blackbox.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:246)
        at top.niunaijun.blackbox.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:139)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4595)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4835)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2921)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9551)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2149)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1777)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at top.niunaijun.blackbox.client.hook.delegate.InstrumentationDelegate.execStartActivity(InstrumentationDelegate.java:359)
        at top.niunaijun.blackbox.client.hook.delegate.AppInstrumentation.execStartActivity(AppInstrumentation.java:222)
        at android.app.Activity.startActivityForResult(Activity.java:5630)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:5554)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zbe(com.google.android.gms:play-services-auth@@20.2.0:6)
        at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(com.google.android.gms:play-services-auth@@20.2.0:14)
        at android.app.Activity.performCreate(Activity.java:8488)
        at android.app.Activity.performCreate(Activity.java:8461)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
        at top.niunaijun.blackbox.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:246)
        at top.niunaijun.blackbox.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:139)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4595)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4835)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:113)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2921)
        at android.os.Handler.dispatchMessage(Handler.java:117)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:293)
        at android.app.ActivityThread.main(ActivityThread.java:9551)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
```

**Comment by scottrules44** [comment]
Are you referring to my personal Google Sign In plugin? That is not a Corona/Solar2D plugin and you should not report issues here

**Comment by scottrules44** [comment]
Assuming your referencing my Google Sign In plugin this has been patched with update
