### ISSUE TITLE
[ANDROID]: Live Build App crashing on startup

### ISSUE THREAD

**Issue by yousaf-shah** [coronalabs/corona#586]
I have noticed on a few of my Android devices that recently when doing a live build and 'send to device and launch' I am getting a crash immediately on startup. This is a project which has been working perfectly for many months/years previously with no recent changes to build settings. I am using the latest version.

The crash takes the form of an instant dialog saying the app stopped working.  After the initial crash the app runs fine BUT ...

The live build only stops and re-launches the FIRST time I make a change and save it.
After the first time, the app ceases to stop and reboot on saving to the project (all other live builds on the network do stop and relaunch).
If I manually stop the app after a livebuild change and re-launch - some of the project re-syncs over but sometimes not all the changes make it.

Its very weird and never seen it anywhere else.

Here is the dump from the console, right up to the first launch, crash and subsequent re-launch:

```
Android build succeeded in 40 seconds
Jun 20 09:33:38.590 Installing and running Kitchen on Lenovo YT-J706F Installing and running Kitchen to Lenovo YT-J706F successfull! rm: /data/local/tmp/CoronaSDK256c7ef825b0f31f25d51b947a9730f6.apk: No such file or directory Starting: Intent { cmp=12/com.ansca.corona.CoronaActivity } Error type 3 Error: Activity class {12/com.ansca.corona.CoronaActivity} does not exist.
Jun 20 09:33:38.591 ----------  Device Log Starts  ----------
Jun 20 09:33:47.525 Lenovo YT-J706F: Slow operation: 290ms so far, now at startProcess: returned from zygote!
Jun 20 09:33:47.535 Lenovo YT-J706F: Slow operation: 296ms so far, now at startProcess: done updating battery stats Lenovo YT-J706F: Slow operation: 297ms so far, now at startProcess: building log message Lenovo YT-J706F: Slow operation: 297ms so far, now at startProcess: starting to update pids map Lenovo YT-J706F: Slow operation: 297ms so far, now at startProcess: done updating pids map
Jun 20 09:33:47.991 Lenovo YT-J706F: Slow operati
Jun 20 09:33:47.992 on: 60ms so far, now at startProcess: returned from zygote!
Jun 20 09:33:48.060 Lenovo YT-J706F: Sch
Jun 20 09:33:48.061 eduling restart of crashed service com.android.chrome/org.chromium.content.app.SandboxedProcessService0:5 in 1000ms for connection
Jun 20 09:33:48.156 Lenovo YT-J706F: Slow operati
Jun 20 09:33:48.157 on: 222ms so far, now at startProcess: done updating battery stats
Jun 20 09:33:48.159 Lenovo YT-J706F: Slow operation: 222ms so far, now at startProcess: building log message Lenovo YT-J706F: Slow operation: 222ms so far, now at startProcess: starting to update pids map Lenovo
Jun 20 09:33:48.169  YT-J706F: Slow operation: 224ms so far, now at startProcess: done updating pids map
Jun 20 09:33:52.106 Lenovo YT-J706F: Slow operation: 51ms so far, now at startProcess: returned from zygote!
Jun 20 09:33:52.115 Lenovo YT-J706F: Sl
Jun 20 09:33:52.115 ow operation: 60ms so far, now at startProcess: done updating battery stats Lenovo YT-J706F: Slow operation: 60ms so far, now at startProcess: building log message Lenovo YT-J706F: Slow operation: 60ms so far, now at startProcess: starting to update pids map Lenovo YT-J706F: Slow operation: 60ms so far, now at startProcess: done updating pids map
Jun 20 09:33:52.356 Lenovo YT-J706F: Slow operation: 62ms so far, now at
Jun 20 09:33:52.357  startProcess: done updating battery stats
Jun 20 09:33:52.357 Lenovo YT-J706F: Slow operation: 63ms so far, now at startProcess: building log message Lenovo YT-J706F: Slow operation: 63ms so far, now at startProcess: starting to update pids map Lenovo YT-J706F: Slow operation: 63ms so far, now at startProcess: done updating pids map
Jun 20 09:34:00.537 Lenovo YT-J706F: Platform: L
Jun 20 09:34:00.538 enovo YT-J706F / ARM64 / 12 / Mali-G76 MC4 / OpenGL ES 3.2 v1.r26p0-01eac0.13ab62fe1abaa04804550bf418d27133 / 2023.3690 / English | GB | en_GB | en
Jun 20 09:34:07.370 Lenovo YT-J706F: stopServiceToken startId 373 is last, but have 1 remaining args
Jun 20 09:34:07.438 Lenovo YT-J706F: Platf
Jun 20 09:34:07.439 orm: Lenovo YT-J706F / ARM64 / 12 / Mali-G76 MC4 / OpenGL ES 3.2 v1.r26p0-01eac0.13ab62fe1abaa04804550bf418d27133 / 2023.3690 / English | G
Jun 20 09:34:07.440 B | en_GB | en
Jun 20 09:34:07.518 Lenovo YT-J706F: [device] COMPOSERLOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSERLOCAL: USING LOCAL COMPOSER MODULE Lenovo YT-J706F: [device] COMPOSERLOCAL: *****************************************
Jun 20 09:34:07.530 Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: USING LOCAL COMPOSER SCENE MODULE
Jun 20 09:34:07.530 Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: *****************************************
Jun 20 09:34:07.558 Lenovo YT-J706F: FATAL EXCEPTION: m
Jun 20 09:34:07.559 ain Lenovo YT-J706F: Process: com.platopusretail.kitchen, PID: 8130 Lenovo YT-J706F: java.lang.RuntimeException: Unable to destroy activity {com.platopusretail.kitchen/com.ansca.corona.CoronaActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void plugin.liveBuild.S
Jun 20 09:34:07.559 yncTask.StopSyncTask()' on a null object reference Lenovo YT-J706F: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5430) Lenovo YT-J706F: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5463) Lenovo YT-J706F: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47) Lenovo YT-J706F: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) Lenovo YT-J706F: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) Lenovo YT-J706F: 	at android.app.servertransaction.TransactionExecutor.e
Jun 20 09:34:07.559 xecute(TransactionExecutor.java:97) Lenovo YT-J706F: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2248) Lenovo YT-J706F: 	at android.os.Handler.dispatchMessage(Handler.java:106) Lenovo YT-J706F: 	at android.os.Looper.loopOn
Jun 20 09:34:07.560 ce(Looper.java:201) Lenovo YT-J706F: 	at android.os.Looper.loop(Looper.java:288) Lenovo YT-J706F: 	at android.app.ActivityThread.main(ActivityThread.java:7884) Lenovo YT-J706F: 	at java.lang.reflect.Method.invoke(Native Method) Lenovo YT-J706F: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Runti
Jun 20 09:34:07.569 meInit.java:568) Lenovo YT-J706F: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) Lenovo YT-J706F: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void plugin.liveBuild.SyncTask.StopSyncTask()' on a null object reference Lenovo YT-J706F: 	at plugin.liveBuild.CoronaLiveSync$CoronaRuntimeEventHandler.onExiting(CoronaLiveSync.java:84) Lenovo YT-J706F: 	at com.ansca.corona.CoronaEnvironment$RuntimeEventHandler.onExiting(CoronaEnvironment.java:549) Lenovo YT-J706F: 	at com.ansca.corona.CoronaRuntime.onExiting(CoronaRuntime.java:479) Lenovo YT-J706F: 	at com.ansca.corona.CoronaRuntime.dispose(CoronaRuntime.java:85) Lenovo YT-J706F: 	at com.ansca.corona.CoronaActivity.onDestroy(CoronaActivi
Jun 20 09:34:07.570 ty.java:1786) Lenovo YT-J706F: 	at android.app.Activity.performDestroy(Activity.java:8604) Lenovo YT-J706F: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364) Lenovo YT-J706F: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5417) Lenovo YT-J706F: 	... 13 more
Jun 20 09:34:07.971 Lenovo YT-J706F: [device] COMPOSERLOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSERLOCAL: USING LOCAL COMPOSER MODULE Lenovo YT-J706F: [device] COMPOSERLOCAL: *****************************************
Jun 20 09:34:07.979 Lenovo YT-J706F: [d
Jun 20 09:34:07.980 evice] COMPOSER_SCENELOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: USING LOCAL COMPOSER SCENE MODULE Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: *****************************************
Jun 20 09:34:12.460 Lenovo YT-J706F: setHasOverlayUi called on unknown pid: 8130
Jun 20 09:34:14.330 Lenovo YT-J706F: Platform: Lenovo YT-J706F / ARM64 / 12 / Mali-G76 MC4 / OpenGL ES 3.2 v1.r26p0-01eac0.13ab62fe1abaa04804550bf418d27133 / 2023.3690 / English | GB | en_GB | en
Jun 20 09:34:14.402 Lenovo YT-J706F: [d
Jun 20 09:34:14.403 evice] COMPOSERL
Jun 20 09:34:14.413 OCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSERLOCAL: USING LOCAL COMPOSER MODULE Lenovo YT-J706F: [device] COMPOSERLOCAL: *********************************
Jun 20 09:34:14.413 ******** Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: USING LOCAL COMPOSER SCENE MODULE Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: *****************************************
Jun 20 09:34:16.239 Lenovo YT-J706F: Platform: Lenovo YT-J706F 
Jun 20 09:34:16.240 / ARM64 / 12 / Mali-G76 MC4 / OpenGL ES 3.2 v1.r26p0-01eac0.13ab62fe1abaa04804550bf418d27133 / 2023.3690 / English | GB | en_GB | en
Jun 20 09:34:16.265 Lenovo YT-J706F: [dev
Jun 20 09:34:16.266 ice] COMPOSERLOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSERLOCAL: USING LOCAL COMPOSER MODULE Lenovo YT-J706F: [device] COMPOSERLOCAL: *****************************************
Jun 20 09:34:16.274 Lenovo YT-J706F: [dev
Jun 20 09:34:16.274 ice] COMPOSER_SCENELOCAL: ***************************************** Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: USING LOCAL COMPOSER SCENE MODULE Lenovo YT-J706F: [device] COMPOSER_SCENELOCAL: *****************************************
Jun 20 09:34:18.870 Lenovo YT-J706F: Unable to start service Intent
Jun 20 09:34:18.871  { act=com.google.android.gms.drive.ApiService.RESET_AFTER_BOOT flg=0x4 cmp=com.google.android.gms/.drive.api.ApiService (has extras) } U=0: not found
```

**Comment by Shchvova** [comment]
Please make sure to attach build.settings. It is possible that some of the plugins causes the issue. Or try commenting out plugins if possible.

**Comment by Shchvova** [comment]
Also, error message hints on deeper issues :(

**Comment by yousaf-shah** [comment]
OK thank you! 🙏 I will do some tests without the plugins and come back with the build.settings

One thing to note is the device in question has a new version of Android 11 with some kind of CPU conservation mode ... maybe its something deeper that needs dealing with!

**Comment by yousaf-shah** [comment]
Really sorry - this turned out to be a weird bug caused by having apps on the device with the same package identifier. They seemed to be getting confused as to which one was getting the livebuild - I deleted both and re-installed and all seems OK - will close for now.
