### ISSUE TITLE
Google billing v2 no longer works with pending purchases since the update to billing library 6

### ISSUE THREAD

**Issue by marksolar2d** [coronalabs/corona#711]
Normal purchases work as expected but [pending/delayed purchases](https://developer.android.com/google/play/billing/integrate#pending) fail.  There is no callback to `storeTransaction(event)`

Tested with live SKUs using this [test code](https://github.com/solar2d/com.solar2d-plugin.google.iap.billing.v2/blob/master/src/Corona/main.lua)

Here is the log

```07-08 14:01:43.282 22496 22549 V Corona  : Loading via reflection: plugin.google.iap.billing.v2.LuaLoader
07-08 14:01:44.923 22496 22549 I Corona  : Transaction event    {
07-08 14:01:44.923 22496 22549 I Corona  :   "name":"init",
07-08 14:01:44.923 22496 22549 I Corona  :   "transaction":{
07-08 14:01:44.923 22496 22549 I Corona  :     "isError":false,
07-08 14:01:44.923 22496 22549 I Corona  :     "state":"initialized"
07-08 14:01:44.923 22496 22549 I Corona  :   }
07-08 14:01:44.923 22496 22549 I Corona  : }
07-08 14:01:44.923 22496 22549 I Corona  : ----------------
07-08 14:01:46.626 22496 22549 I Corona  : Product list event   {
07-08 14:01:46.626 22496 22549 I Corona  :   "invalidProducts":[],
07-08 14:01:46.626 22496 22549 I Corona  :   "name":"productList",
07-08 14:01:46.626 22496 22549 I Corona  :   "products":[{
07-08 14:01:46.626 22496 22549 I Corona  :       "priceAmountMicros":"990000",
07-08 14:01:46.626 22496 22549 I Corona  :       "originalJson":"{\"title\":\"bag of money\",\"description\":\"Purchase a bag of money\",\"productId\":\"\",\"type\":\"inapp\",\"packageName\":\"\",\"localizedPrice\":\"£0.99\",\"price_amount_micros\":990000,\"price_currency_code\":\"GBP\"}",
07-08 14:01:46.626 22496 22549 I Corona  :       "description":"bag of money",
07-08 14:01:46.626 22496 22549 I Corona  :       "priceCurrencyCode":"GBP",
07-08 14:01:46.626 22496 22549 I Corona  :       "productIdentifier":"",
07-08 14:01:46.626 22496 22549 I Corona  :       "localizedPrice":"£0.99",
07-08 14:01:46.626 22496 22549 I Corona  :       "type":"inapp",
07-08 14:01:46.626 22496 22549 I Corona  :       "title":""
07-08 14:01:46.626 22496 22549 I Corona  :     }]
07-08 14:01:46.626 22496 22549 I Corona  : }
07-08 14:01:46.626 22496 22549 I Corona  : ----------------
07-08 14:01:51.395 22496 22549 I Corona  : JavaToNativeShim.pause(runtime)
07-08 14:01:51.406 22496 22496 I Corona  : controller.getGLView().onPause()
07-08 14:02:02.327 22496 22549 I Corona  : JavaToNativeShim.resume(runtime)
07-08 14:02:02.335 22496 22549 I Corona  : controller.requestRender()
07-08 14:02:02.335 22496 22549 E Corona  : StoreTransactionRuntimeTask: dispatching Google IAP storeTransaction event
07-08 14:02:02.335 22496 22549 E Corona  : java.lang.NullPointerException: null
07-08 14:02:02.335 22496 22549 E Corona  :      at com.naef.jnlua.LuaState.lua_pushstring(Native Method)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.naef.jnlua.LuaState.pushString(LuaState.java:691)
07-08 14:02:02.335 22496 22549 E Corona  :      at plugin.google.iap.billing.v2.StoreTransactionRuntimeTask.executeUsing(StoreTransactionRuntimeTask.java:86)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.CoronaRuntimeTaskDispatcher$TaskEvent.Send(CoronaRuntimeTaskDispatcher.java:179)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.events.EventManager.sendEvents(EventManager.java:100)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.Controller.updateRuntimeState(Controller.java:372)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame(CoronaGLSurfaceView.java:434)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1625)
07-08 14:02:02.335 22496 22549 E Corona  :      at com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1380)```

**Comment by Shchvova** [comment]
Thank you for reporting. Fixed plugin is up

**Comment by marksolar2d** [comment]
Getting there...  but `event.transaction.identifier` is an empty string then the purchase is delayed.  I cache this between sessions to know if the purchase was previously made in a different session and to award the player.

```07-08 19:10:31.006  4344 11045 I Corona  : table: 0xb400006e3b157900 {
07-08 19:10:31.006  4344 11045 I Corona  :   [name] => "storeTransaction"
07-08 19:10:31.006  4344 11045 I Corona  :   [transaction] => table: 0xb400006e3b157900 {
07-08 19:10:31.006  4344 11045 I Corona  :                      [identifier] => ""```

This value is correct on normal purchases.  Thanks.

**Comment by Shchvova** [comment]
I see... It seems that now [getOrderId](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getOrderId()) which is matched to the `identifier` field won't be set unless state is `purchased`.

**Comment by marksolar2d** [comment]
Well that's a serious breaking change since v5!  What would you recommend?
